import { MaterialInfo, MaterialColor } from '../types';

export const MATERIALS_DATA: Record<string, MaterialInfo> = {
  PLA: {
    key: 'PLA',
    name: 'PLA Estándar / Plus',
    category: 'FDM',
    density: 1.24,
    basePricePerGram: 0.045,
    tempResistanceMax: 55,
    tensileStrength: 48,
    flexibility: 'Rígido',
    uvResistance: 'Baja',
    description: 'Termoplástico ecológico a base de almidón de maíz. Gran precisión dimensional, excelente acabado superficial y ausencia de olor o deformaciones.',
    bestFor: 'Prototipado conceptual, maquetas arquitectónicas, figuras, soportes de bajo esfuerzo y piezas decorativas.',
    recommendedInfill: 20,
  },
  PETG: {
    key: 'PETG',
    name: 'PETG Industrial',
    category: 'FDM',
    density: 1.27,
    basePricePerGram: 0.055,
    tempResistanceMax: 72,
    tensileStrength: 52,
    flexibility: 'Semi-rígido',
    uvResistance: 'Alta',
    description: 'Combina la facilidad del PLA con la resistencia del ABS. Gran resistencia a impactos, impermeabilidad, apto para contacto alimentario y resistente a químicos.',
    bestFor: 'Piezas mecánicas cotidianas, carcasas electrónicas estancas, piezas para exteriores moderados y utillajes industriales.',
    recommendedInfill: 35,
  },
  ABS: {
    key: 'ABS',
    name: 'ABS Técnico',
    category: 'FDM',
    density: 1.04,
    basePricePerGram: 0.052,
    tempResistanceMax: 95,
    tensileStrength: 43,
    flexibility: 'Rígido',
    uvResistance: 'Media',
    description: 'Plástico de ingeniería resistente al calor, choques y torsión. Se puede mecanizar, taladrar, lijar y alisar mediante vapor de acetona.',
    bestFor: 'Componentes automotrices interiores, carcasas de electrodomésticos, engranajes y piezas que soportan calor hasta 95°C.',
    recommendedInfill: 40,
  },
  ASA: {
    key: 'ASA',
    name: 'ASA Ultra-UV (Intemperie)',
    category: 'FDM',
    density: 1.07,
    basePricePerGram: 0.065,
    tempResistanceMax: 95,
    tensileStrength: 45,
    flexibility: 'Rígido',
    uvResistance: 'Excelente',
    description: 'Evolución del ABS formulado con acrilato. Inmune a la degradación por radiación solar ultravioleta, lluvia, nieve y cambios bruscos de temperatura.',
    bestFor: 'Piezas para el exterior bajo sol directo permanente, náutica, accesorios para vehículos y señalización exterior.',
    recommendedInfill: 40,
  },
  TPU: {
    key: 'TPU',
    name: 'TPU 95A Flexible',
    category: 'FDM',
    density: 1.21,
    basePricePerGram: 0.075,
    tempResistanceMax: 78,
    tensileStrength: 35,
    flexibility: 'Flexible (95A)',
    uvResistance: 'Alta',
    description: 'Elastómero termoplástico flexible similar al caucho de neumático. Increíble resistencia a la abrasión, desgaste continuo y amortiguación de vibraciones.',
    bestFor: 'Juntas y sellos estancos, fundas protectoras antichoque, topes de amortiguación, correas y calzado técnico.',
    recommendedInfill: 30,
  },
  RESINA_UV: {
    key: 'RESINA_UV',
    name: 'Resina Fotopolímero UV (SLA)',
    category: 'SLA',
    density: 1.15,
    basePricePerGram: 0.095,
    tempResistanceMax: 65,
    tensileStrength: 60,
    flexibility: 'Muy rígido',
    uvResistance: 'Alta',
    description: 'Impresión estereolitográfica láser/pantalla LCD de micro-resolución (hasta 0.025 mm). Superficie lisa sedosa sin líneas de capa visibles.',
    bestFor: 'Modelos de ultra-alta precisión, joyería, odontología, miniaturas coleccionables y moldes maestros para silicona.',
    recommendedInfill: 100, // Resin parts are usually solid or hollowed with high thickness
  },
};

export const COLOR_OPTIONS: MaterialColor[] = [
  { name: 'Negro Mate', hex: '#1e293b' },
  { name: 'Blanco Puro', hex: '#f8fafc' },
  { name: 'Gris Industrial', hex: '#64748b' },
  { name: 'Azul Corporativo', hex: '#1e6091' },
  { name: 'Rojo Carmesí', hex: '#dc2626' },
  { name: 'Naranja Mecánico', hex: '#ea580c' },
  { name: 'Verde Táctico', hex: '#16a34a' },
  { name: 'Amarillo Señal', hex: '#eab308' },
  { name: 'Translúcido / Natural', hex: '#cbd5e1' },
];

export const LAYER_HEIGHT_OPTIONS = [
  {
    value: 0.12,
    label: '0.12 mm · Ultra-Fina',
    badge: 'Máximo detalle',
    description: 'Acabado casi liso, ideal para esculturas o piezas con roscas milimétricas.',
    speedFactor: 1.7,
  },
  {
    value: 0.16,
    label: '0.16 mm · Alta Calidad',
    badge: 'Recomendado',
    description: 'Excelente compromiso entre suavidad visual y tiempo de fabricación.',
    speedFactor: 1.3,
  },
  {
    value: 0.20,
    label: '0.20 mm · Estándar',
    badge: 'Más popular',
    description: 'Calidad industrial estándar. Muy buena resistencia mecánica.',
    speedFactor: 1.0,
  },
  {
    value: 0.28,
    label: '0.28 mm · Rápida',
    badge: 'Económico',
    description: 'Laminado grueso para prototipos rápidos de validación volumétrica.',
    speedFactor: 0.75,
  },
];

export const INFILL_PRESETS = [
  { percent: 15, label: '15% Visual', desc: 'Decorativo / maquetas' },
  { percent: 30, label: '30% Estándar', desc: 'Uso general funcional' },
  { percent: 55, label: '55% Reforzado', desc: 'Soportes y mecanismos' },
  { percent: 100, label: '100% Sólido', desc: 'Carga pesada / roscas' },
];

export const POST_PROCESSING_OPTIONS = [
  {
    id: 'none' as const,
    name: 'Sin postprocesado (Estándar)',
    costPerUnit: 0,
    description: 'Retirada limpia de soportes básicos y despegue de la cama de impresión.',
    badge: 'Incluido',
  },
  {
    id: 'sanding' as const,
    name: 'Retirada de soportes y pulido fino',
    costPerUnit: 3.50,
    description: 'Lijado manual progresivo al agua para suavizar líneas de capa visibles en superficies exteriores.',
    badge: '+3.50€ / ud',
  },
  {
    id: 'painting' as const,
    name: 'Pintado / Imprimado profesional',
    costPerUnit: 8.00,
    description: 'Imprimación de adherencia bicomponente y lacado en cabina con esmalte industrial de alta resistencia.',
    badge: '+8.00€ / ud',
  },
  {
    id: 'inserts' as const,
    name: 'Inserto de roscas metálicas (Heat-Set)',
    costPerUnit: 4.50,
    description: 'Inserción térmica de tuercas de latón (M3/M4/M5) en orificios para soportar ensamblajes y pares de apriete continuos.',
    badge: '+4.50€ / ud',
  },
];

